

set(RDEBUG_DIRECTORIES ${CMAKE_CURRENT_LIST_DIR}/../rdebug)
set(RDEBUG_EXECUTABLE_FILES
        ${CMAKE_CURRENT_LIST_DIR}/SEGGER_RTT_ASM_ARMv7M.S
        ${CMAKE_CURRENT_LIST_DIR}/SEGGER_RTT_Syscalls_GCC.c
        ${CMAKE_CURRENT_LIST_DIR}/SEGGER_RTT.c
        ${CMAKE_CURRENT_LIST_DIR}/SEGGER_RTT_printf.c)




